### ISSUE TITLE
Added value

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/Amazon-AWS#4]
I like the idea of this plugin but am unclear how it is any different than simply having a JavaScript of the the AWS library.

**Comment by EddyVerbruggen** [comment]
Good question and you're right, you might as well use the JS version without this as a wrapper. Some users might appreciate these added features though:
- This plugin offers a one-click way to add it to a Telerik AppBuilder project. We even have a demo app link to from our [documentation](http://plugins.telerik.com/cordova/plugin/amazon-aws).
- It auto-wires the AWS credentials for you upon `deviceready` so you don't need to worry about it.
